//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAMEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDepartment
    {
        public int Id { get; set; }
        public Nullable<int> fk_department { get; set; }
        public Nullable<int> fk_company { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
    }
}
